name: Test

on:
  push:
    branches:
      - master
    tags-ignore: ["v[0-9]+.[0-9]+.[0-9]+*"]
    paths:
      - "**.ts"
      - "package*"
      - "yarn*"
      - "*.json"
      - "*.js"
      - "*rc"
      - ".github/workflows/**.yml"
  pull_request:
    branches:
      - "*"
    tags-ignore: ["v[0-9]+.[0-9]+.[0-9]+*"]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn --silent

      - name: Test
        run: yarn test
